### ISSUE TITLE
issue loading on server?

### ISSUE THREAD

**Issue by CharleeToombs** [EwyBoy/Quick-Harvest#11]
###### **Minecraft Version**
1.16.4

###### **Forge Version**
35.1.4

###### **Mod Version**
1.16-1.1.1

###### **Expected behavior**
Server expected to run. 
This same server worked last night (it was the first run!) Today, however it does not!

###### **Actual Behavior**
server fails to start up, and crash report implicates this mod (lack of config file?)... 
once this mod was removed server successfully booted...

###### **Link to Crashlog or Forgelog** *[If Applicable]*
https://drive.google.com/file/d/1Bo7EGL7s5xVHiLBi12sTR53S4Ay53Uba/view?usp=sharing

###### **Steps to reproduce** *[If Applicable]*
unclear? I'm not certain why this started

**Comment by Lyricalfox** [comment]
This isn't a fix, I'm super sorry, but I also had this problem on my server! I use Apex Hosting, and we run Forge 1.16.4 as our .jar. We compared your crashlog to ours, and it appears to throw the same exact error - we removed the mod from our server in order to run it again, but if you want me to toss it back on to screenshot the error again, let me know.

**Comment by CharleeToombs** [comment]
Just a tip... I opted to switch to Reap.. does the same thing but seems to function on my server 😄

**Comment by EwyBoy** [comment]
Currently on Christmas vacation so unknown eta for a fix. Looks indeed like there is a bug with the config. 

Potential temporary fix is to either remove the mod or experiment with taking the server config generated by the client and copy/paste it into the server folder to replace the broken config. Or delete the config and se if the servers can generate a new config.

It could very well be that the second time the server is started, the config system (night config) that is used by Forge is trying to validate the config and something wrong is happening here.

The config is only validated if the config is not generated fresh and there already is an existing config file there. Perhaps that's the reason it only occurs during the second server launch and form then on.

Thanks for the reports everyone. I will update this thread once a solution is published.

**Comment by LukeGi** [comment]
This should be fixed now, try the new version on curseforge!
