### ISSUE TITLE
Building sugarcane / kelp / cactus etc on top of itself bug.

### ISSUE THREAD

**Issue by EwyBoy** [EwyBoy/Quick-Harvest#14]
###### **Minecraft Version**
> any

###### **Forge Version**
> Does not matter

###### **Mod Version**
>  any

###### **Expected behavior**
> When trying to build a very tall cactus or sugarcane tower in survival, I expect you be able to place a cactus / kelp / sugarcane etc.. on top of a cactus without harvesting it.

###### **Actual Behavior**
> It breaks the block and consumes the item from my hand resulting in a negative dupe bug where my itemstack is reduced by one for each action I perform and no building is accomplished.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> None

###### **Steps to reproduce** *[If Applicable]*
> Go into survival mode. Cheat in a stack of 64 cactus / kelp / sugarcane etc..
Try to build a very tall cactus / kelp / sugarcane etc.. and watch it fail and consume the stack 1 by 1.

**Comment by EwyBoy** [comment]
I played with the mod on my server and my friends found this very annoying that they cannot place a cactus on top of another cactus and also found the negative dupe bug in the process.

Would be nice if you held the item you were attempting to quick harvest it would not trigger and instead let you build to prevent this.

**Comment by LukeGi** [comment]
Pressing shift while placing or changing the config would solve this problem. Perhaps we should change the default config.

**Comment by EwyBoy** [comment]
Any way we could get the side clicked and do a check if (Side == EnumFacing.UP &&  blockstate == this).
So if you are clicking sugarcane with a sugarcane blockitem on the top facing side there is a huge change the player is actually attempting to place it on top and not harvest.
