### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by MarcellPohl** [EwyBoy/Quick-Harvest#17]
###### **Minecraft Version**
1.17.1

###### **Forge Version**
37.0.53

###### **Mod Version**
Quick+Harvest-1.17.1-1.4.0.jar

###### **Describe the bug**
Quick Harvest (quickharvest) has failed to load correctly
java.lang.reflect.InvocationTargetExcaption: null

###### **How to reproduce**
I have the following mods inside:
Optiforge-MC1.17.1-0.1.0.jar
journeymap-1.17.1.5.7.3rc3.jar
MouseTweaks-2.14mc1.17.1.jar
Quick+Harvest-1.17.1-1.4.0.jar

###### **Link to [crashlog](https://gist.github.com/)** *[If Applicable]*
https://drive.google.com/file/d/1fMHh2ajNjwp7RFOrukDquDUiQ1nFEZd5/view?usp=sharing

###### **Screenshots / Images**
![image](https://user-images.githubusercontent.com/78857846/132102965-12f5afe6-d072-46f1-bbce-2e8fdee46043.png)

**Comment by EwyBoy** [comment]
Sorry it took me forever to fix this..
It works now and is fixed.

Download: https://www.curseforge.com/minecraft/mc-mods/quick-harvest/files/3496093

Thank you for reporting this issue.
