### ISSUE TITLE
Doesn´t work with 1.15.2, but the mod description says it does.

### ISSUE THREAD

**Issue by DasFantatier** [EwyBoy/Quick-Harvest#6]
###### **Minecraft Version**
> 1.15.2

###### **Forge Version**
> 31.1.0

###### **Mod Version**
> latest 1.15.1-1.0.1.jar

###### **Expected behavior**
> Mod site says it´s working with 1.15.2

###### **Actual Behavior**
> Doesn´t work with 1.15.2 - Error message appears when connecting "quickharvest need 1.15.1 - you are using 1.15.2

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> No Log needed

###### **Steps to reproduce** *[If Applicable]*
> Everytime when connecting

**Comment by EwyBoy** [comment]
https://www.curseforge.com/minecraft/mc-mods/quick-harvest/files/2914428
